### ISSUE TITLE
run.bat issue

### ISSUE THREAD

**Issue by snailman06** [xKynn/PathOfExileRPC#7]
when i run regular run i get:

`C:\Users\snail\Downloads\PathOfExileRPC-master>python launcher.py
Traceback (most recent call last):
  File "C:\Users\snail\Downloads\PathOfExileRPC-master\launcher.py", line 13, in <module>
    from progressbar import ProgressBar, Percentage, RotatingMarker, ETA, FileTransferSpeed, Bar
ModuleNotFoundError: No module named 'progressbar'

C:\Users\snail\Downloads\PathOfExileRPC-master>pause
Press any key to continue . . .`

when i run as admin i get:

`C:\WINDOWS\system32>python launcher.py
python: can't open file 'C:\\WINDOWS\\system32\\launcher.py': [Errno 2] No such file or directory

C:\WINDOWS\system32>pause
Press any key to continue . . .`

if i try to run via the launcher version i get :

`INFO:__main__:Waiting for path of exile to launch...
INFO:__main__:Found path of exile log at C:/Program Files (x86)/Grinding Gear Games/Path of Exile/logs/Client.txt
INFO:__main__:Log monitor has started
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<PoeRPC.monitor_log() done, defined at C:\Users\demol\Documents\PathOfExileRPC\poeRPC.py:295> exception=ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'")>
Traceback (most recent call last):
  File "C:\Users\demol\Documents\PathOfExileRPC\poeRPC.py", line 312, in monitor_log
  File "C:\Users\demol\Documents\PathOfExileRPC\poeRPC.py", line 259, in handle_log_event
  File "C:\Users\demol\Documents\PathOfExileRPC\poeRPC.py", line 97, in fetch_char
  File "C:\Users\demol\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 1027, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
`

**Comment by xKynn** [comment]
Try opening command prompt and typing "python -m pip install progressbar" without the quotes
