### ISSUE TITLE
ERROR: asyncio 

### ISSUE THREAD

**Issue by MikuArt** [xKynn/PathOfExileRPC#8]
Hello! 

I got an error on both .exe and .bat about the asyncio so can't use it do you have an idea on how to fix it? :(
Im using python 3.10 is that bad?

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<PoeRPC.monitor_log() done, defined at C:\Users\******\Desktop\PathOfExileRPC-master\poeRPC.py:295> exception=ContentTypeError(RequestInfo(url=URL('https://www.pathofexile.com/character-window/get-characters?accountName=MikuArt'), method='GET', headers=<CIMultiDictProxy('Host': 'www.pathofexile.com', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.1')>, real_url=URL('https://www.pathofexile.com/character-window/get-characters?accountName=MikuArt')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Date': 'Sun, 06 Feb 2022 11:48:21 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6d9426217d6aee58-CDG', 'Content-Encoding': 'gzip')>)>
Traceback (most recent call last):
  File "C:\Users\******\Desktop\PathOfExileRPC-master\poeRPC.py", line 312, in monitor_log
    await self.handle_log_event(log)
  File "C:\Users\******\Desktop\PathOfExileRPC-master\poeRPC.py", line 259, in handle_log_event
    await self.fetch_char()
  File "C:\Users\******\Desktop\PathOfExileRPC-master\poeRPC.py", line 97, in fetch_char
    js = await resp.json()
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.pathofexile.com/character-window/get-characters?accountName=MikuArt')

**Comment by DankAlighieri** [comment]
I believe that its a problem with the type of data that is collected. Im trying to figure some workaround, if i get anything, ill let you know.

**Comment by xKynn** [comment]
Is this still an issue @DankAlighieri ? I haven't looked at this project in a while, if you join my support server at https://discord.gg/hUWQ5fJ I can try to take a look at it / help.

**Comment by DankAlighieri** [comment]
Yeah, i couldn't figure it out how to convert the data to something that the client could read.
